[cluster01]
  monitoring-basedir = "system"
  monitoring-datadir = "/var/lib/replication-manager"
  monitoring-sharedir = "/opt/replication-manager/share"
  monitoring-confdir = "/etc/replication-manager"
  monitoring-ticker = 2
  monitoring-socket = ""
  monitoring-tunnel-host = ""
  monitoring-tunnel-credential = ""
  monitoring-address = "192.168.0.41"
  monitoring-write-heartbeat = false
  monitoring-write-heartbeat-credential = ""
  monitoring-schema-change = true
  monitoring-schema-change-script = ""
  monitoring-queries = true
  monitoring-long-query-time = 10000
  monitoring-long-query-script = ""
  monitoring-scheduler = true
  verbose = true
  log-file = ""
  log-syslog = false
  log-level = 0
  log-sst = false
  db-servers-credential = "root:mariadb"
  db-servers-hosts = "127.0.0.1:3333,127.0.0.1:3334"
  db-servers-tls-ca-cert = ""
  db-servers-tls-client-key = ""
  db-servers-tls-client-cert = ""
  db-servers-prefered-master = "127.0.0.1:3333"
  db-servers-ignored-hosts = ""
  db-servers-connect-timeout = 1
  db-servers-read-timeout = 15
  db-servers-binary-path = "/usr/local/mysql/bin"
  db-servers-locality = "127.0.0.1"
  proxy-servers-read-on-master = false
  replication-master-connect-retry = 10
  replication-credential = "root:mariadb"
  replication-source-name = ""
  replication-use-ssl = false
  replication-multi-master-ring = false
  replication-multi-master-wsrep = false
  replication-multi-master = false
  replication-multi-tier-slave = false
  replication-master-slave-never-relay = true
  switchover-wait-kill = 5000
  switchover-wait-trx = 10
  switchover-wait-write-query = 10
  switchover-at-equal-gtid = false
  switchover-at-sync = false
  switchover-max-slave-delay = 0
  switchover-slave-wait-catch = true
  failover-limit = 5
  failover-pre-script = ""
  failover-post-script = ""
  failover-readonly-state = true
  failover-time-limit = 0
  failover-at-sync = false
  failover-event-scheduler = false
  failover-event-status = false
  failover-restart-unsafe = false
  failover-reset-time = 0
  failover-mode = "manual"
  failover-max-slave-delay = 30
  failover-falsepositive-ping-counter = 5
  failover-falsepositive-heartbeat = true
  failover-falsepositive-maxscale = false
  failover-falsepositive-heartbeat-timeout = 3
  failover-falsepositive-maxscale-timeout = 14
  failover-falsepositive-external = false
  failover-falsepositive-external-port = 80
  autorejoin = true
  autorejoin-flashback = false
  autorejoin-mysqldump = false
  autorejoin-zfs-flashback = false
  autorejoin-physical-backup = false
  autorejoin-logical-backup = false
  autorejoin-script = ""
  autorejoin-backup-binlog = true
  autorejoin-flashback-on-sync = true
  autorejoin-flashback-on-unsync = false
  autorejoin-slave-positional-heartbeat = false
  check-type = "tcp"
  check-replication-filters = true
  check-binlog-filters = true
  check-grants = true
  check-replication-state = true
  force-slave-heartbeat = false
  force-slave-heartbeat-time = 3
  force-slave-heartbeat-retry = 5
  force-slave-gtid-mode = false
  force-slave-no-gtid-mode = false
  force-slave-semisync = false
  force-slave-readonly = false
  force-binlog-row = false
  force-binlog-annotate = false
  force-binlog-compress = false
  force-binlog-slowqueries = false
  force-binlog-checksum = false
  force-inmemory-binlog-cache-size = false
  force-disk-relaylog-size-limit = false
  force-disk-relaylog-size-limit-size = 1000000000
  force-sync-binlog = false
  force-sync-innodb = false
  force-noslave-behind = false
  http-bind-address = "0.0.0.0"
  http-port = "10001"
  http-server = true
  http-root = "/opt/replication-manager/share/dashboard"
  http-auth = false
  http-bootstrap-button = false
  http-session-lifetime = 3600
  mail-from = "mrm@localhost"
  mail-to = ""
  mail-smtp-addr = "localhost:25"
  heartbeat-table = false
  extproxy = false
  extproxy-address = ""
  shardproxy = true
  shardproxy-servers = "127.0.0.1:3336"
  shardproxy-user = "root:mariadb"
  shardproxy-copy-grants = true
  maxscale = false
  maxscale-servers = ""
  maxscale-port = "6603"
  maxscale-user = "admin"
  maxscale-pass = "mariadb"
  maxscale-write-port = 3306
  maxscale-read-port = 3307
  maxscale-read-write-port = 3308
  maxscale-maxinfo-port = 3309
  maxscale-binlog = false
  maxscale-binlog-port = 3309
  maxscale-disable-monitor = false
  maxscale-get-info-method = "maxadmin"
  maxscale-server-match-port = false
  myproxy = false
  myproxy-port = 4000
  myproxy-user = "admin"
  myproxy-password = "repman"
  haproxy = true
  haproxy-servers = ""
  haproxy-write-port = 3306
  haproxy-read-port = 3307
  haproxy-stat-port = 1988
  haproxy-ip-write-bind = "0.0.0.0"
  haproxy-ip-read-bind = "0.0.0.0"
  haproxy-binary-path = "/usr/local/bin/haproxy"
  proxysql = false
  proxysql-servers = ""
  proxysql-port = "6033"
  proxysql-admin-port = "6032"
  proxysql-user = "admin"
  proxysql-password = "admin"
  proxysql-writer-hostgroup = "0"
  proxysql-reader-hostgroup = "1"
  proxysql-copy-grants = true
  proxysql-bootstrap = false
  mysqlrouter = false
  mysqlrouter-servers = ""
  mysqlrouter-port = ""
  mysqlrouter-user = ""
  mysqlrouter-pass = ""
  mysqlrouter-write-port = 0
  mysqlrouter-read-port = 0
  mysqlrouter-read-write-port = 0
  sphinx = false
  sphinx-servers = "127.0.0.1"
  sphinx-config = "/opt/replication-manager/share/sphinx/sphinx.conf"
  sphinx-sql-port = "9306"
  sphinx-port = "9312"
  registry-consul = false
  registry-servers = "127.0.0.1"
  graphite-metrics = false
  graphite-embedded = false
  graphite-carbon-host = "127.0.0.1"
  graphite-carbon-port = 2003
  graphite-carbon-api-port = 10002
  graphite-carbon-server-port = 10003
  graphite-carbon-link-port = 7002
  graphite-carbon-pickle-port = 2004
  graphite-carbon-pprof-port = 7007
  sysbench-binary-path = "/usr/local/bin/sysbench"
  sysbench-time = 100
  sysbench-threads = 4
  arbitration-external = true
  arbitration-external-secret = "13787932529099014144"
  arbitration-external-hosts = "reparb.signal18.io:80"
  arbitration-external-unique-id = 0
  arbitration-peer-hosts = "127.0.0.1:10002"
  arbitrator-bind-address = ""
  arbitrator-driver = ""
  test = true
  test-inject-traffic = false
  enterprise = false
  opensvc-host = ""
  opensvc-register = false
  opensvc-admin-user = ""
  opensvc-user = ""
  opensvc-codeapp = ""
  prov-db-localhost-binary-path = ""
  prov-db-service-type = ""
  prov-db-agents = ""
  prov-db-memory = ""
  prov-db-disk-iops = ""
  prov-db-cpu-cores = ""
  prov-db-tags = ""
  prov-db-disk-size = ""
  prov-db-disk-fs = ""
  prov-db-disk-pool = ""
  prov-db-disk-device = ""
  prov-db-disk-type = ""
  prov-db-disk-snapshot-prefered-master = false
  prov-db-disk-snapshot-keep = 0
  prov-db-net-iface = ""
  prov-db-net-mask = ""
  prov-db-net-gateway = ""
  prov-db-docker-img = ""
  prov-db-datadir-version = "10.2"
  prov-db-load-sql = ""
  prov-db-load-csv = ""
  prov-proxy-service-type = ""
  prov-proxy-agents = ""
  prov-proxy-disk-size = ""
  prov-proxy-disk-fs = ""
  prov-proxy-disk-pool = ""
  prov-proxy-disk-device = ""
  prov-proxy-disk-type = ""
  prov-proxy-net-iface = ""
  prov-proxy-net-mask = ""
  prov-proxy-net-gateway = ""
  prov-proxy-route-addr = ""
  prov-proxy-route-port = ""
  prov-proxy-route-mask = ""
  prov-proxy-route-policy = ""
  prov-proxy-docker-shardproxy-img = ""
  prov-proxy-docker-maxscale-img = ""
  prov-proxy-docker-haproxy-img = ""
  prov-proxy-docker-proxysql-img = ""
  prov-proxy-docker-mysqlrouter-img = ""
  prov-proxy-tags = ""
  prov-sphinx-agents = ""
  prov-sphinx-docker-img = ""
  prov-sphinx-memory = ""
  prov-sphinx-disk-size = ""
  prov-sphinx-cpu-cores = ""
  prov-sphinx-max-childrens = ""
  prov-sphinx-disk-pool = ""
  prov-sphinx-disk-fs = ""
  prov-sphinx-disk-device = ""
  prov-sphinx-disk-type = ""
  prov-sphinx-tags = ""
  prov-sphinx-reindex-schedule = ""
  prov-sphinx-service-type = ""
  prov-tls-server-ca = ""
  prov-tls-server-cert = ""
  prov-tls-server-key = ""
  prov-net-cni = false
  prov-net-cni-cluster = ""
  prov-docker-daemon-private = false
  api-credential = "admin:repman"
  api-port = "10005"
  api-bind = "0.0.0.0"
  alert-script = ""
  backup = false
  scheduler-db-servers-logical-backup = true
  scheduler-db-servers-physical-backup = true
  scheduler-db-servers-logs = true
  scheduler-db-servers-optimize = true
  scheduler-db-servers-logical-backup-cron = "0 0 1 * * 6"
  scheduler-db-servers-physical-backup-cron = "0 0 0 * * *"
  scheduler-db-servers-logs-cron = "0/10 * * * *"
  scheduler-db-servers-optimize-cron = "0 0 3 1 * 5"
  backup-logical-type = "mysqldump"
  backup-physical-type = "xtrabackup"
  backup-keep-hourly = 1
  backup-keep-daily = 1
  backup-keep-weekly = 1
  backup-keep-monthly = 1
  backup-keep-yearly = 1
  backup-repo = "directory"
  backup-repo-aws-key = ""
  backup-repo-aws-secret = ""
  backup-repo-aws-uri = ""
